### ISSUE TITLE
Help wanted: Concise package list

### ISSUE THREAD

**Issue by YaguraStation** [GoogleContainerTools/base-images-docker#223]
I have difficulties finding the actual list of installed packages and tools in this repo. This would be beneficial to update the Dockerfile in case of a change.

**Comment by tejal29** [comment]
@YaguraStation Can you provide more info on which image ?

**Comment by tejal29** [comment]
For Ubuntu, we install these packages
https://github.com/GoogleContainerTools/base-images-docker/blob/master/ubuntu/BUILD#L60

For debian, 
We install the following 2 packages.
https://github.com/GoogleContainerTools/base-images-docker/blob/master/debian/reproducible/mkimage.sh#L36
We will add these in the respective READMEs .

Thanks
Tejal

**Comment by tejal29** [comment]
Please feel free to send a PR and i will help you get this in.

**Comment by YaguraStation** [comment]
@tejal29 Thanks. The questioned was about Debian. I also saw your answer, yesterday, thanks. 

I was surprised of only two packages (netbase, ca-certificates) being installed, because from my previous experience a bunch of other tools were readily available!? But I'd need to invest more time in research and it's going to be the same as inventorying the vanilla image and keeping my own tabs, I guess. I'll follow your advice and send in a PR.
