### ISSUE TITLE
Ubuntu16_04 image has CMD set to "/tmp/installer.sh"

### ISSUE THREAD

**Issue by xingao267** [GoogleContainerTools/base-images-docker#225]
$ docker pull gcr.io/cloud-marketplace/google/ubuntu16_04@sha256:5125aac627c68226c6ad6083d0e3419bc6252bea1eb9d6e7258ecfd67233d655
sha256:5125aac627c68226c6ad6083d0e3419bc6252bea1eb9d6e7258ecfd67233d655: Pulling from cloud-marketplace/google/ubuntu16_04
Digest: sha256:5125aac627c68226c6ad6083d0e3419bc6252bea1eb9d6e7258ecfd67233d655
Status: Image is up to date for gcr.io/cloud-marketplace/google/ubuntu16_04@sha256:5125aac627c68226c6ad6083d0e3419bc6252bea1eb9d6e7258ecfd67233d655

$ docker inspect gcr.io/cloud-marketplace/google/ubuntu16_04@sha256:5125aac627c68226c6ad6083d0e3419bc6252bea1eb9d6e7258ecfd67233d655

It shows the CMD is set to "/tmp/installer.sh", which doesn't seem to be right?

I checked the debian8 one, it was set to  
           [
                "/bin/sh",
                "-c",
                "/bin/bash"
            ],

**Comment by xingao267** [comment]
@dlorenc

**Comment by xingao267** [comment]
cc @nlopezgi @erain FYI

**Comment by erain** [comment]
Thanks for looking into this @xingao267 !

**Comment by tejal29** [comment]
Thanks @xingao267 Will take a look.

**Comment by sharifelgamal** [comment]
This is fixed.
