### ISSUE TITLE
Bug: Using download_pkgs and install_pkgs in base dir fails

### ISSUE THREAD

**Issue by ArthurRab** [GoogleContainerTools/base-images-docker#235]
When called in the base dir, [this replace](https://github.com/GoogleContainerTools/base-images-docker/blob/0d0080ed000d0ad00489d87e0016e05000a6937f/package_managers/download_pkgs.bzl#L42) matches [this path](https://github.com/GoogleContainerTools/base-images-docker/blob/0d0080ed000d0ad00489d87e0016e05000a6937f/package_managers/download_pkgs.bzl#L35) and replaces it as well, causing the file not to be found.

**Comment by tejal29** [comment]
Thanks! Feel free to send a PR
