### ISSUE TITLE
Are the Ubuntu images still a work in progress?

### ISSUE THREAD

**Issue by krismolendyke** [GoogleContainerTools/base-images-docker#276]
The [current README.md](https://github.com/GoogleContainerTools/base-images-docker/blob/7be0b9052d84255a1e7af26cbb384404ad026d56/ubuntu/README.md) states that the Ubuntu images are still works in progress and that the builds are not reproducible.  I'm not sure what reproducibility means in this context, too.

The [commits](https://github.com/GoogleContainerTools/base-images-docker/blame/7be0b9052d84255a1e7af26cbb384404ad026d56/ubuntu/README.md) that update that portion of the `README.md` were made around a year ago.  Is this still accurate?  Nothing in the [managed base images documentation](https://cloud.google.com/container-registry/docs/managed-base-images) mentions WIP or reproducibility.  Similarly, nothing [in the marketplace](https://console.cloud.google.com/marketplace/details/google/ubuntu1804) make any such mention.

Are these Ubuntu images production ready?

Thanks!

**Comment by dlorenc** [comment]
Ah, sorry for the confusion. These images are production ready! We'll get this github documentation sorted out.

**Comment by krismolendyke** [comment]
Excellent, thanks!  I figured that was the case 😉
